"""add ml_anomaly_score to login_events

Revision ID: 1740a9a63e26
Revises: 471a915a7b9c
Create Date: 2026-09-20 14:56:37.202310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1740a9a63e26'
down_revision: Union[str, None] = '471a915a7b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_events', sa.Column('ml_anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_events', 'ml_anomaly_score')
    # ### end Alembic commands ###
