"""mr13_alert_intelligence_family_dedup_priority

Revision ID: 222f3d1610a6
Revises: e1318f3ac8e5
Create Date: 2026-09-27 15:24:09.126092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222f3d1610a6'
down_revision: Union[str, None] = 'e1318f3ac8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('attack_family_confidence', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('alerts', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('importance', sa.Float(), server_default='1.0', nullable=False))
    # tay thêm (không phải autogenerate): tra cứu chống trùng lặp lọc theo đúng 3 cột này (xem alert_intelligence.find_dedup_target)
    op.create_index('ix_alerts_dedup_lookup', 'alerts', ['user_id', 'attack_family', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_dedup_lookup', table_name='alerts')
    op.drop_column('users', 'importance')
    op.drop_column('alerts', 'priority_score')
    op.drop_column('alerts', 'last_seen_at')
    op.drop_column('alerts', 'occurrence_count')
    op.drop_column('alerts', 'attack_family_confidence')
    # ### end Alembic commands ###
