"""mr17_rule_overrides

Revision ID: 832bb849e97d
Revises: c257dbc325be
Create Date: 2026-09-28 08:14:35.618366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832bb849e97d'
down_revision: Union[str, None] = 'c257dbc325be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_overrides',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_overrides')
    # ### end Alembic commands ###
