"""mr15_user_risk_profiles

Revision ID: 889725c2f003
Revises: 222f3d1610a6
Create Date: 2026-09-27 19:08:00.435090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889725c2f003'
down_revision: Union[str, None] = '222f3d1610a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_risk_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('threshold_delta', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('feedback_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('false_positive_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_risk_profiles')
    # ### end Alembic commands ###
