"""mr12 realtime integration: asn/ua/device cols, hybrid score, campaigns/blocklist/response_actions/audit_log/model_registry

Revision ID: e1318f3ac8e5
Revises: 1740a9a63e26
Create Date: 2026-09-27 12:55:20.850110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1318f3ac8e5'
down_revision: Union[str, None] = '1740a9a63e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=64), server_default='admin', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_blocklist_kind_value')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('attack_family', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('profile_path', sa.Text(), nullable=True),
    sa.Column('feature_signature', sa.String(length=32), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_registry_name_version')
    )
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_event_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='recommended', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['login_event_id'], ['login_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_login_event_id'), 'response_actions', ['login_event_id'], unique=False)
    op.add_column('alerts', sa.Column('rule_id', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('attack_family', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('explanation', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('status', sa.String(length=16), server_default='open', nullable=False))
    op.add_column('alerts', sa.Column('feedback', sa.Text(), nullable=True))
    op.create_foreign_key('fk_alerts_campaign_id', 'alerts', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('login_events', sa.Column('asn', sa.Integer(), nullable=True))
    op.add_column('login_events', sa.Column('os_name', sa.String(length=64), nullable=True))
    op.add_column('login_events', sa.Column('browser_name', sa.String(length=64), nullable=True))
    op.add_column('login_events', sa.Column('device_type', sa.String(length=16), nullable=True))
    op.add_column('login_events', sa.Column('hybrid_risk_score', sa.Integer(), nullable=True))
    op.add_column('login_events', sa.Column('hybrid_action', sa.String(length=16), nullable=True))
    op.create_index('ix_login_events_asn', 'login_events', ['asn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_events_asn', table_name='login_events')
    op.drop_column('login_events', 'hybrid_action')
    op.drop_column('login_events', 'hybrid_risk_score')
    op.drop_column('login_events', 'device_type')
    op.drop_column('login_events', 'browser_name')
    op.drop_column('login_events', 'os_name')
    op.drop_column('login_events', 'asn')
    op.drop_constraint('fk_alerts_campaign_id', 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'feedback')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'campaign_id')
    op.drop_column('alerts', 'explanation')
    op.drop_column('alerts', 'attack_family')
    op.drop_column('alerts', 'rule_id')
    op.drop_index(op.f('ix_response_actions_login_event_id'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_table('model_registry')
    op.drop_table('campaigns')
    op.drop_table('blocklist')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
